CREATE TABLE [dbo].[Formats]
(
	[Id] UNIQUEIDENTIFIER PRIMARY KEY,
	[Name] NVARCHAR(100) NOT NULL UNIQUE,
	[IsActive] BIT DEFAULT 1,
	[CreatedAt] DATETIME NOT NULL DEFAULT SYSUTCDATETIME(),
	[UpdatedAt] DATETIME NULL ,
	[CreatedBy] UNIQUEIDENTIFIER NOT NULL,
	[UpdatedBy] UNIQUEIDENTIFIER NULL
)
