CREATE TABLE [dbo].[Images]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	[ReleaseId] UNIQUEIDENTIFIER NULL,
    [ArtistId] UNIQUEIDENTIFIER NULL,
    [LabelId] UNIQUEIDENTIFIER NULL,
    [ImageUrl] NVARCHAR(2048) NOT NULL,
    [IsPrimary] BIT DEFAULT 0,
    [SortOrder] INT DEFAULT 0,
    FOREIGN KEY (ReleaseId) REFERENCES Releases(Id) ON DELETE CASCADE,
    FOREIGN KEY (ArtistId) REFERENCES Artists(Id) ON DELETE CASCADE,
    FOREIGN KEY (LabelId) REFERENCES Labels(Id) ON DELETE CASCADE
)
