CREATE TABLE [dbo].[Labels]
(
	[Id] INT IDENTITY(1,1) PRIMARY KEY,
	[Name] NVARCHAR(100) NOT NULL UNIQUE,
	[Profile] NVARCHAR(MAX) NULL,
	[IsActive] BIT DEFAULT 1,
	[CreatedAt] DATETIME NOT NULL DEFAULT SYSUTCDATETIME(),
	[UpdatedAt] DATETIME NULL ,
	[CreatedBy] INT NOT NULL,
	[UpdatedBy] INT NULL
)
