CREATE TABLE [dbo].[Users]
(
	[Id] INT IDENTITY(1,1) PRIMARY KEY,
	[Username] NVARCHAR(50) NOT NULL UNIQUE,
	[Email] NVARCHAR(100) NOT NULL UNIQUE,
	[CreatedAt] DATETIME NOT NULL DEFAULT SYSUTCDATETIME(),
	[UpdatedAt] DATETIME NULL,
	[CreatedBy] INT NOT NULL,
	[UpdatedBy] INT NULL,
	[IsActive] BIT DEFAULT 1,
	[LastLoginAt] DATETIME NULL
)
