CREATE TABLE [dbo].[Users]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	[Username] NVARCHAR(50) NOT NULL UNIQUE,
	[Email] NVARCHAR(100) NOT NULL UNIQUE,
	[CreatedAt] DATETIME NOT NULL DEFAULT SYSUTCDATETIME(),
	[UpdatedAt] DATETIME NULL,
	[CreatedBy] UNIQUEIDENTIFIER NOT NULL,
	[UpdatedBy] UNIQUEIDENTIFIER NULL,
	[IsActive] BIT DEFAULT 1,
	[LastLoginAt] DATETIME NULL
)
